//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentDataViewer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StudentDataViewer.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Student.
        /// </summary>
        public static string AddStudentTitle {
            get {
                return ResourceManager.GetString("AddStudentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Student.
        /// </summary>
        public static string ButtonAddNewStudent {
            get {
                return ResourceManager.GetString("ButtonAddNewStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Student.
        /// </summary>
        public static string ButtonAddStudent {
            get {
                return ResourceManager.GetString("ButtonAddStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ButtonDeleteStudent {
            get {
                return ResourceManager.GetString("ButtonDeleteStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit student.
        /// </summary>
        public static string ButtonEditStudent {
            get {
                return ResourceManager.GetString("ButtonEditStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string ButtonNo {
            get {
                return ResourceManager.GetString("ButtonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string ButtonYes {
            get {
                return ResourceManager.GetString("ButtonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIDS.
        /// </summary>
        public static string DepartmentAIDS {
            get {
                return ResourceManager.GetString("DepartmentAIDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CIVIL.
        /// </summary>
        public static string DepartmentCIVIL {
            get {
                return ResourceManager.GetString("DepartmentCIVIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSE.
        /// </summary>
        public static string DepartmentCSE {
            get {
                return ResourceManager.GetString("DepartmentCSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT.
        /// </summary>
        public static string DepartmentIT {
            get {
                return ResourceManager.GetString("DepartmentIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MECH.
        /// </summary>
        public static string DepartmentMECH {
            get {
                return ResourceManager.GetString("DepartmentMECH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        public static string SectionA {
            get {
                return ResourceManager.GetString("SectionA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        public static string SectionB {
            get {
                return ResourceManager.GetString("SectionB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        public static string SectionC {
            get {
                return ResourceManager.GetString("SectionC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPA.
        /// </summary>
        public static string TitleCGPA {
            get {
                return ResourceManager.GetString("TitleCGPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string TitleDepartment {
            get {
                return ResourceManager.GetString("TitleDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Student.
        /// </summary>
        public static string TitleEditStudent {
            get {
                return ResourceManager.GetString("TitleEditStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string TitleName {
            get {
                return ResourceManager.GetString("TitleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        public static string TitleSection {
            get {
                return ResourceManager.GetString("TitleSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Data List.
        /// </summary>
        public static string TitleStudentDataList {
            get {
                return ResourceManager.GetString("TitleStudentDataList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StudentId.
        /// </summary>
        public static string TitleStudentId {
            get {
                return ResourceManager.GetString("TitleStudentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Data Viewer.
        /// </summary>
        public static string TitleText {
            get {
                return ResourceManager.GetString("TitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string TitleYear {
            get {
                return ResourceManager.GetString("TitleYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string Year1 {
            get {
                return ResourceManager.GetString("Year1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string Year2 {
            get {
                return ResourceManager.GetString("Year2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string Year3 {
            get {
                return ResourceManager.GetString("Year3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string Year4 {
            get {
                return ResourceManager.GetString("Year4", resourceCulture);
            }
        }
    }
}
